import type { Metadata } from 'next'
import { Lora } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/context/AuthContext'
import Background3D from '@/components/Background3D'

const inter = Lora({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Background3D />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
